version: '3.4'

# envs https://medium.com/softonic-eng/docker-compose-from-development-to-production-88000124a57c

services:

  rich-puppeteer:
    image: damoeb/rich-rss:puppeteer-0.1
    restart: always
    security_opt:
      - seccomp=chrome.json
    networks:
      - puppeteer

  rss-proxy:
    image: damoeb/rss-proxy:2.0.0-beta
    restart: always
    depends_on:
      - rich-puppeteer
    ports:
      - "8080:8080"
    environment:
      - LOG_LEVEL=info
      # -- CHANGE THIS --
      - APP_PUBLIC_URL=http://localhost:8080
      - TOKEN_SECRET=1234_top_secret
      - PUPPETEER_HOST=http://rich-puppeteer:3000
    networks:
      - puppeteer

networks:
  puppeteer:
    driver: bridge
